import { useState, type ChangeEvent, type FormEvent } from 'react'
import { Navigate, useNavigate } from 'react-router-dom'
import { getAuthService, useAuth } from '../auth'

export function SetupAdminPage() {
  const { user } = useAuth(); const navigate = useNavigate()
  const [form, setForm] = useState({ setupCode: '', email: '', password: '', pin: '', confirmation: '' })
  const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false)
  if (user?.role === 'super_admin') return <Navigate to="/map" replace />
  const update = (key: keyof typeof form) => (event: ChangeEvent<HTMLInputElement>) => setForm({ ...form, [key]: event.target.value })
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(null); if (!/^\d{6}$/.test(form.pin) || form.pin !== form.confirmation) { setError('Enter matching six-digit PINs.'); return }; setSaving(true); try { await getAuthService().bootstrapAdmin({ setupCode: form.setupCode, email: form.email, password: form.password, pin: form.pin }); navigate('/map', { replace: true }) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to complete administrator setup.') } finally { setSaving(false) } }
  return <main className="login-page login-experience"><div className="login-page__card"><header className="login-page__header"><p className="login-page__eyebrow">First administrator</p><h1 className="login-page__title">Set up ASG access</h1><p className="login-page__subtitle">Create your Firebase account and administrator PIN.</p></header><form className="login-page__form" onSubmit={submit}><label className="form-label" htmlFor="setup-code">One-time setup code</label><input id="setup-code" className="form-input" type="password" value={form.setupCode} onChange={update('setupCode')} required /><label className="form-label" htmlFor="setup-email">Administrator email</label><input id="setup-email" className="form-input" type="email" value={form.email} onChange={update('email')} required /><label className="form-label" htmlFor="setup-password">Firebase password</label><input id="setup-password" className="form-input" type="password" minLength={10} value={form.password} onChange={update('password')} required /><label className="form-label" htmlFor="setup-pin">Administrator PIN</label><input id="setup-pin" className="form-input" type="password" inputMode="numeric" maxLength={6} value={form.pin} onChange={update('pin')} required /><label className="form-label" htmlFor="setup-pin-confirm">Confirm administrator PIN</label><input id="setup-pin-confirm" className="form-input" type="password" inputMode="numeric" maxLength={6} value={form.confirmation} onChange={update('confirmation')} required />{error && <p className="login-page__error" role="alert">{error}</p>}<button className="btn btn--primary btn--block" disabled={saving}>{saving ? 'Creating…' : 'Create administrator'}</button></form></div></main>
}
